### ISSUE TITLE
Firmware size too big

### ISSUE THREAD

**Issue by hexapoder** [ku-fpg/haskino#1]
I followed the instructions to upload the firmware to my Arduino Uno . After compiling, i get the error that  sketch is too big : 32.712 byte (%101). Max : 32.256byte. 

Is this firmware designed for bigger boards? It compiles ok if i choose mega board.  

OS X 10.11.3

**Comment by markgrebe** [comment]
It is intended to be used for the Uno, as well as larger boards.  I have just recently added back in the Servo and Stepper libraries, and that may be what is causing it to exceed the flash limit for you.  In my builds on the Uno, I am still very slightly under the limit, but that may be because I am using a command line build as opposed to the IDE, and the compiler options may be different.
I have also added conditional compilation of command type handling, so you should be able to get it small enough to run on an UNO if you are not using all of the interfaces.
In HaskinoConfig.h, at the end of the file there are several defines for each of the modules.  For example, if you are not using I2C, then change #define INCLUDE_I2C_CMDS to
#undef INCLUDE_I2C_CMDS.  (and the same for One Wire, Server, or Stepper, or other interfaces  you are not using).
I may add some additional configuration in the near future to control other aspects of the language that may not be used.

**Comment by hexapoder** [comment]
I guess you are speaking about HaskinoComm.cpp. I was able to upload to UNO playing with this file.

**Comment by markgrebe** [comment]
Actually, I was speaking about HaskingConfig.h, but I need to apologize. When I added the conditional compilation, I forgot to push the last two changes to github.  If you pull the latest version, you will find the conditional compilation macros now in that header file.

**Comment by hexapoder** [comment]
Works fine on my Uno.
